# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-13 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1024)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.AppUser')),
            ],
        ),
    ]
