# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='user_friends', to='register.AppUser')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
